[package]
name = "fcm_decrypt"
version = "0.1.0"
authors = ["Bikramaditya Meher <bikramadityameher20@gmail.com>"]

[[bin]]
name = "fcm_decrypt"
path = "main.rs"

[dependencies]
ece = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.0"